version: 0.1

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  type: zip
  files:
    - dist/**/*
    - package.json
    - package-lock.json
    - Procfile